[build-system]
requires = ["setuptools"]

[project]
name = "CDX-Writer"
version = "0.4.5"
requires-python = ">3.10,<=3.14"
dependencies = [
    "warctools>=4.10.0",
    "surt==0.3.1",
]

[project.optional-dependencies]
textfeatures = [
    "lxml[html_clean]==6.0.2",
    "pycld2==0.42",
    "simhash-pybind==0.0.3",
]
test = [
    "pytest==9.0.2",
]

[project.scripts]
cdx_writer = "cdx_writer.command:main"
