[build-system]
requires = ["setuptools"]

[project]
name = "CDX-Writer"
version = "0.4.5"
requires-python = ">=3.11"
dependencies = [
    "warctools>=4.10.0",
    "surt==0.3.1",
]

[project.optional-dependencies]
textfeatures = [
    "lxml[html_clean]",
    "pycld2",
    "simhash",
]
test = [
    "pytest<5",
]

[project.scripts]
cdx_writer = "cdx_writer.command:main"
